group=de.verdox.solarminer

frontendVersion=1.1.5
coreVersion=1.1.4
pcAgentVersion=1.1.7
pvApiVersion=1.0.0

frontendImage=verdox/solar-miner
coreImage=verdox/solar-miner-core
pcAgentImage=verdox/solar-miner-pc-agent

pvApiSnapshotsRepository=https://repo.verdox.de/snapshots
pvApiReleasesRepository=https://repo.verdox.de/releases


productionMode = true
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m
