spring.application.name=pc-agent
server.port=8084
solarminer.pearl.experimental-enabled=true
solarminer.agent.proxy.monero-port=3335
solarminer.agent.proxy.pearl-port=3334
solarminer.agent.proxy.discovery-port=8091
solarminer.agent.proxy.api-port=8090
springdoc.paths-to-match=/api/**
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
