spring.application.name=Solarminer.app - Local node
vaadin.enabled=false
vaadin.launch-browser=false
spring.messages.encoding=UTF-8

spring.flyway.fail-on-missing-locations=false
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

solarmining.backend.url.rest=${BACKEND_URL:https://lightning.solarminer.app:443}
solarmining.backend.url.socket=${BACKEND_WS_URL:wss://lightning.solarminer.app:443/lightning-tunnel}
solarmining.core.url=${CORE_MICRO_SERVICE_URL:http://localhost:8082/api/miners}
solarmining.currency-service.url=${CURRENCY_MICRO_SERVICE_URL:http://localhost:8081}
solarmining.phoenix.url=${PHOENIXD_BACKEND_URL:http://localhost:9740}
solarmining.phoenix.config=${PHOENIX_CONFIG_PATH:./app/phoenixd/phoenix.conf}
solarmining.phoenix.seed=${PHOENIX_SEED_PATH:./app/phoenixd/seed.dat}

influxdb.org=${INFLUXDB_ORG:SolarMiner}
influxdb.bucket=${INFLUXDB_BUCKET:solarminer}
influxdb.url=${INFLUXDB_URL:http://localhost:8086}

spring.datasource.url=${MYSQL_URL:jdbc:mariadb://localhost:3306/solarminer}
spring.datasource.username=${MYSQL_USER:solarminer}

influxdb.token=${INFLUXDB_ADMIN_TOKEN}
spring.datasource.password=${MYSQL_PASSWORD}
