package de.verdox.pv_miner.pvsite.inverter;

import de.verdox.pv_miner.influx.QueryResult;

/**
 * Data Transfer Object representing the real-time status of a solar inverter.
 * This DTO focuses on the power generation (DC side) and power conversion (AC side),
 * as well as the hardware health of the inverter.
 */
public record InverterDataDTO(
        /**
         * The total raw direct current (DC) power currently generated by the solar panels, in Watts.
         */
        int currentDcPowerW,

        /**
         * The current direct current (DC) voltage from the solar strings, in Volts.
         */
        double currentDcVoltageV,

        // --- AC Side (Grid Output) ---

        /**
         * The actual alternating current (AC) power currently outputted by the inverter into the house net, in Watts.
         */
        int currentAcPowerW,

        /**
         * The current alternating current (AC) grid voltage measured by the inverter, in Volts (usually around 230V).
         */
        double currentAcVoltageV,

        /**
         * The current AC grid frequency, in Hertz (usually around 50.0 Hz in Europe).
         */
        double gridFrequencyHz,

        // --- History & Hardware Status ---

        /**
         * The total energy yielded by this inverter over its entire lifetime, in Watt-hours.
         */
        long totalEnergyYieldWh,

        /**
         * The internal temperature of the inverter's power electronics, in degrees Celsius.
         */
        double internalTemperatureC,

        /**
         * The vendor-specific status or error code (e.g., 0 for Normal Operation, 1 for Standby, etc.).
         */
        int statusCode
) implements QueryResult {
    public static final InverterDataDTO DEFAULT = new InverterDataDTO(0,0,0,0,0,0,0,0);
}
