spring.application.name=currency-rates

spring.datasource.url=jdbc:h2:file:/app/data/currency_rates;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

server.tomcat.threads.max=15
server.tomcat.threads.min-spare=5
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.locations=classpath:db/migration