spring.application.name=currency-rates
server.port=8080

spring.datasource.url=jdbc:h2:file:/workspace/data/currency_rates;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

server.tomcat.threads.max=15
server.tomcat.threads.min-spare=5
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

spring.flyway.locations=classpath:db/migration